apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lacriminalite-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
    - host: lacriminalite.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lacriminalite-web
                port:
                  number: 80
  tls:
    - hosts:
        - lacriminalite.ru
      secretName: lacriminalite-tls
